### ISSUE TITLE
It is way too hard to avoid including panicking and formatting infrastructure code

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/team#19]
Even though panicking just translates into a `trap` without any diagnostic messages, we still include tons of `being_panic_fmt` etc type code. This has a *huge* code size footprint: ~75% of my code size *after* `wasm-gc`!

I had to write [`wasm-snip`](https://github.com/fitzgen/wasm-snip) pretty much just for removing panicking and formatting infrastructure. But that is just a stop-gap, not a solution: it is fragile and manual.

**Comment by est31** [comment]
You could theoretically install a panic hook. Which is what I have done in one of my wasm projects in order to be able to find out what the panic was about.

**Comment by pepyakin** [comment]
My experience (although it is more -emscripten like) is that changing `panic_fmt` to something that doesn't touches it's args and building with LTO will remove most of the `Display`/`Debug` machinery and [data from segments](https://github.com/aturon/rust-wasm/issues/21#issuecomment-358404859)

However, there was still problems: sometimes this strings wasn't removed despite the fact `panic_fmt` was almost empty and "Arguments" parameter was dead. 
As I can remember, I managed to solve this issue by running additional LLVM passes: deadargelim and some globals cleaning pass, over the final `.ll` file.

**Comment by fitzgen** [comment]
> You could theoretically install a panic hook. Which is what I have done in one of my wasm projects in order to be able to find out what the panic was about.

Can one change the panic hook without resorting to unstable features?

**Comment by est31** [comment]
@fitzgen yes, the panic hook API is stable: https://doc.rust-lang.org/stable/std/panic/fn.set_hook.html

Generally I don't object to an option that allows you to turn off all panic related things but there should be an option to keep the panic machinery, especially [as we can't emit any source maps on the unknown target yet](https://github.com/rust-lang/rust/issues/46765). I know this is a bit hard given that cargo can't recompile std :/.

**Comment by fitzgen** [comment]
> Generally I don't object to an option that allows you to turn off all panic related things but there should be an option to keep the panic machinery, especially as we can't emit any source maps on the unknown target yet. I know this is a bit hard given that cargo can't recompile std :/.

Crate authors could optionally set the panic hook based on a cargo feature.

If setting a custom panic hook really does get rid of *all* this bloat, then we should document how to do this somewhere and then close this issue.

**Comment by fitzgen** [comment]
Oh, and devtools show the disassembly, and if you have the "name" section, also show function names, which should help for debugging.

**Comment by est31** [comment]
@fitzgen I'm aware. They don't show the file name and line though.

**Comment by est31** [comment]
> If setting a custom panic hook really does get rid of all this bloat, then we should document how to do this somewhere and then close this issue.

There are two mechanisms:

* setting the `panic_fmt` lang item. This does allow you to get rid of most of the panic formatting machinery (that's why it is used in an [embedded framework](https://github.com/japaric/cortex-m-rt/blob/42388316d9b1647e7f70cb762a84112200b6df9e/src/lang_items.rs#L5) as well) . It requires `#[no_std]` and right now it also requires nightly.
* the panic hook mechanism through the `std::panic::set_hook` function. This one doesn't really optimize out anything. I guess because the hook needs to changed during runtime :).

To make the first option work on stable, @japaric [has written RFC 2070](https://github.com/rust-lang/rfcs/pull/2070), but it still has to be implemented ([tracking issue](https://github.com/rust-lang/rust/issues/44489)).

We can't really use this as we are no `#[no_std]` application. Maybe we could make the compiler allow later `#[panic_implementation]` invocations to override earlier ones somehow with a smart trick^TM. In order for this to work, LTO still needs to be able to optimize out the now dead code. Maybe this is not really possible. No idea. However, if xargo gets integrated into cargo, we can finally compile the entirety of libstd with `panic=abort` which would be the best resolution to this entire question.

**Comment by koute** [comment]
> However, if xargo gets integrated into cargo, we can finally compile the entirety of libstd with panic=abort which would be the best resolution to this entire question.

I feel like having `xargo` integrated into `cargo` would solve a few of our other problems and points of contention too.

In the meantime I *guess* just going `#[no_std]` is going to be the best bet in getting the tiniest code footprint? Well, that or manually sniping parts of the `.wasm` file.

**Comment by mgattozzi** [comment]
@fitzgen I'm still working on #12 but once it lands if that does work we should add it there as a resource. Even a whole section on reducing binary size would be good.

**Comment by pepyakin** [comment]
> However, there was still problems: sometimes this strings wasn't removed despite the fact panic_fmt was almost empty and "Arguments" parameter was dead.

It seems that it is also issue for wasm32-unknown-unknown target.
I've created an issue https://github.com/rust-lang/rust/issues/47526.

**Comment by gamozolabs** [comment]
I'm so glad so many people are having these issues. I've been working on an RFC for a while (since December) on making a fmtless panic, as it is crazy that the core of the language (panic) requires one of the most bloated parts of core. I didn't really work on the RFC seriously as I thought I was the only one with this issue and it wouldn't go anywhere.

I'll start to prioritize it.

Currently the model is to have an opt-in fmt-less panic routine, perhaps just provides source file and line number (which for embedded targets is glorious debugging as is).

**Comment by gamozolabs** [comment]
I slightly disagree with @alexcrichton here. While I always agree that we should minimize panics where they are not needed (there's no reason to not do this).

Further I agree that there should really be no way of removing panics. They are fundamental to the language and should be kept. However there needs to be a way of implementing a panic that just does something like `core::intrinsics::abort()` and there should be almost no panic cost (this is up to the optimizer to delete arguments that are unused, which it does fine with fat LTO).

However fundamentally the internals of Rust have panics which are formatted. This is great, for normal use it's nice to see that you indexed X bytes out of bounds or something. However a single use of `core::fmt` is extremely expensive, even in the simplest case (_see examples below_, 1485 bytes increase in code size for a _single_ panic). Unless you can remove all panics, for each uniquely formatted type (str, padding, number, float, hex, etc) used in a panic there is going to be a tremendous amount of code introduced. For a moderate sized codebase that I have, this `core::fmt` `.code` section size increase is near 20 KiB, leading to me not being able to use the `msg` format at all in `panic_fmt`. I simply cannot touch it without going over code size requirements.

There has to be a solution beyond just reducing panic use, and I think it has to be generic. Not a case-by-case remove some panics here and some panics there.

I think there needs to be an optional panic routine that only takes static strings. This would be a nightmare for backwards compatibility as every panic would need to have a non-formatted alternative. However I think the solution is simpler. Just repr the actual format string. This is ugly, but if you are really that critical of code size then you have to make some sacrifices.

For example with a model like this for a bounds check panic you would get something like:

`fn panic_static(msg: &'static str, file &'static str, line: u32, column: u32) -> ! {}`

For something like a `panic_bounds_check` this `msg` string would be literally: `index out of bounds: the len is {} but the index is {}`. It's not as useful as having numbers, however it tells you what the issue is (out of bounds), requires no changes of internal Rust code or existing panics, and can easily be deduped by the compiler to only exist once in `.data`. Making multiple uses of this panic negligible in `.data` size, and have no cost in `.code` size as they won't bring in format routines.

Might not be the ideal panic message, but keep in mind without something like this I cannot get _any_ message at all. I have to go entirely off of file and line (which honestly is pretty great for embedded work).

-------------------------------------------------

For example this code (built with `rustc -C lto -O -Z thinlto=off -g main.rs`):

```
#![no_std]
#![feature(lang_items, start, core_intrinsics)]

#[lang = "panic_fmt"]
#[no_mangle]
pub extern fn rust_begin_panic(msg: core::fmt::Arguments,
                               _file: &'static str,
                               _line: u32,
                               _column: u32) -> ! {
    unsafe {
        core::ptr::read_volatile(&msg);
        core::intrinsics::abort();
    }
}

#[lang = "eh_personality"]
#[no_mangle]
pub extern fn rust_eh_personality() {}

#[start]
#[no_mangle]
#[allow(non_snake_case)]
pub fn mainCRTStartup(_argc: isize, _argv: *const *const u8) -> isize
{
    panic!("WOO");
}
```

Has the code distribution:

![image](https://user-images.githubusercontent.com/13505090/35125622-31529600-fc5f-11e7-87a8-9cdc335b7435.png)

However by changing this code to have a potential panic due to a bounds check this code massively changes:

```
#![no_std]
#![feature(lang_items, start, core_intrinsics)]

#[lang = "panic_fmt"]
#[no_mangle]
pub extern fn rust_begin_panic(msg: core::fmt::Arguments,
                               _file: &'static str,
                               _line: u32,
                               _column: u32) -> ! {
    unsafe {
        core::ptr::read_volatile(&msg);
        core::intrinsics::abort();
    }
}

#[lang = "eh_personality"]
#[no_mangle]
pub extern fn rust_eh_personality() {}

#[start]
#[no_mangle]
#[allow(non_snake_case)]
pub fn mainCRTStartup(_argc: isize, _argv: *const *const u8) -> isize
{
    let x = [1, 2, 3, 4];
    x[_argc as usize]
}
```

![image](https://user-images.githubusercontent.com/13505090/35125664-5506fa28-fc5f-11e7-8c52-5421ecf0fc29.png)

Just by panicing with a bounds check added 1485 bytes of code (not data).

-B

**Comment by fitzgen** [comment]
See also https://github.com/rust-lang-nursery/rfcs/issues/41

**Comment by fitzgen** [comment]
> I don't think it's worthwhile to blanket shoot for "remove everything at all costs" because panics are actually quite useful when debugging and such.

I think that one should be able to create `.wasm` binaries completely stripped of panic and formatting infra, but also have a cargo feature that enables it for debugging and development.

**Comment by RReverser** [comment]
Looks like this should help quite a bit too: https://github.com/rust-lang/rust/issues/54981#issuecomment-443369450 (silent aborts, unfortunately also requires Xargo but it's a good step)

**Comment by ashleygwilliams** [comment]
@fitzgen i think we want to track this issue differently- i'm going to close (if i'm wrong tho please reopen and apologies!)

**Comment by JeanMertz** [comment]
@ashleygwilliams, could you let us know if/when this is being tracked in a different issue?

I am subscribed to this thread because I’m interested in whatever progress is being made on this, but maybe there is another way to stay in the loop?

**Comment by sffc** [comment]
It makes perfect sense that in a debug build, you should get the full panicking infrastructure, but in a release build, you should be able to enable a feature that replaces all panics with a free call to abort().

Has such a feature been made available since the last update on this issue thread?

**Comment by MendyBerger** [comment]
> Has such a feature been made available since the last update on this issue thread?

Think this is what you were looking for https://github.com/rust-lang/rust/issues/54981#issuecomment-899917784

**Comment by sffc** [comment]
Yes, building std with `panic_immediate_abort` is a solution that now solves this issue.
