### ISSUE TITLE
Explain the state and perspective in laymen's terms

### ISSUE THREAD

**Issue by NeverGivinUp** [rustwasm/team#33]
I'm having a hard time understanding what the state and progress of rust-wasm is and means for me. Please explain for someone not versed in compiling, linking and ABI.

I'm considering writing web-app with emberjs and the d3 graphics library that talks to a back-end. I have a lot of concept work to do yet, so I will not be coding before summer/late summer. I'm expecting the project to take at least a full year. To stick to a single language, I'd like to program front- and back-end in rust -- but can I? This is a decision I feel I should make rather early, to be prepared, when the time comes. 

So my questions are as follows: 

1. What are the components for the toolchain and wasm specification, necessary for such a project? 
2. How far along are they?
3. What compromises/limitations would choosing this combination entail at which point in time?

**Comment by est31** [comment]
> To stick to a single language, I'd like to program front- and back-end in rust -- but can I?

*Technically* you must use JavaScript in some regard, as right now it is needed to initiate WebAssembly modules, as well as allowing WebAssembly modules to manipulate the DOM and access other things that JS has access to.

From a *practical* background, you can code most of your application logic in Rust, only using JavaScript for the communication with the client's API. I've done something like this myself but it is certainly not a 6 lane street, more like a game trail.

Note that right now, the WebAssembly support that Rust provides is very early, so breakage is possible.

> What are the components for the toolchain and wasm specification, necessary for such a project?

https://github.com/rust-lang-nursery/rust-wasm#the-crate-ecosystem

So only very few libraries. If you are coming from an SPA perspective, wanting to have a heavy frontend, Rust is really really weak at this right now. But Rust does support a serialized DOM (HTML) approach with libraries for serverside templating, DB access, etc.

So you definitely get the full pioneer experience. Don't bet money on it yet, but if you are up for experimentation, please do so!

**Comment by mgattozzi** [comment]
> I'd like to program front- and back-end in rust -- but can I?

No you'll need JS still for more complicated things depending on what you're trying to do and like you said you're using Ember and d3 so you're not using just wasm. You can supplement the JS with wasm. wasm would best be suited to optimize code paths that might be slow. Take a look at [this excellent article](https://hacks.mozilla.org/2018/01/oxidizing-source-maps-with-rust-and-webassembly/) that goes more detail into that.

> What are the components for the toolchain and wasm specification, necessary for such a project?

You'll need Rust installed using [rustup](https://rustup.rs/) and then:

```bash
$ rustup install nightly
$ rustup target add wasm32-unknown-unknown --toolchain nightly
```
will make sure you have the wasm backend. You'll want to also grab [wasm-gc](https://github.com/alexcrichton/wasm-gc) for now since the unoptimized build has a lot of bugs. My PR (#12) isn't done yet but it should make this easier hopefully by explaining all of this stuff and list more limitations.

I would reccomend maybe consider using [parcel](https://parceljs.org/) they recently added drop in support for rust files. Add some files with the `.rs ` extension, add what functions you want in wasm with the `#[no_mangle]` attribute on them and you should be able to call them like normal

> How far along are they?

This is all early stage stuff. Maybe in a few months when you start things will be better, but be prepared for frustration as you are using the bleeding edge.

> What compromises/limitations would choosing this combination entail at which point in time?

You won't be able to return strings to JS [without some work](https://stackoverflow.com/questions/41353389/how-can-i-return-a-javascript-string-from-a-webassembly-function), you're limited to your return types being numbers or arrays of numbers, you can't manipulate the dom from wasm without making a call out to JS.

wasm has more features being discussed to add to it as a standard but what is currently supported by browsers is limited with what it can do. If you're okay with that and don't mind then go ahead with it, but be prepared with what you're getting into. The full rust stack you envision (like a MEAN one) is not there yet I think, but I do want it to be someday!

**Comment by CryZe** [comment]
> add what functions you want in wasm with the #[no_mangle] attribute on them and you should be able to call them like normal

I'd like to add that your functions need to also have to have the C ABI, so a function needs to look like this:

```rust
#[no_mangle]
pub extern "C" fn my_external_function() { ... }
```

**Comment by NeverGivinUp** [comment]
Thanks for the super fast replies everybody!

I do understand that the frameworks are not wasm and thus I wouldn't be using just wasm. But I'd like to code as if (!) those were just some rust libraries I'd imported. In an ideal world, I'd run a script that would create a rust wrapper on any JS library/framework and after that, the fact, that I'm talking to non-rust components would be transparent. I do understand that the rust-wasm-js connection is far from this vision. But how far, I can't imagine. Is it months or years? Is it even technically possible?

**Comment by CryZe** [comment]
There's a few generators that allow you to generate high level JS / TS libraries for your Rust wasm code. Alex Crichton made one [wasm-bindgen](https://github.com/alexcrichton/wasm-bindgen) and I also made one for my own project [generated high level bindings](https://gist.github.com/CryZe/73571a7d475202783866e77af4467f3b). So I think there's a lot of progress happening in this space :)

**Comment by NeverGivinUp** [comment]
@CryZe Oh, this is interesting. I'll need to experiment with that. Can you give me a comparison of wasm-bindgen and livesplit?

**Comment by CryZe** [comment]
If anything you probably want to go for wasm-bindgen as that has a much nicer API and is actually meant to be used with other projects. Mine on the other hand is heavily tied to my project (and thus heavily opinionated and has a few hacks for a few things) but is also not just tied to wasm, as it allows me to generate high level bindings for 11 languages (+ variations like TypeScript vs. JavaScript, emscripten vs. native wasm backend vs. node, ...) for my project. So mine isn't actually meant for just the web, but is so restricted to my project that it's not really in a usable state for any other project. However with some cleaning up + usage of procedural macros and some other work, it could actually be made into a general purpose bindgen project for everyone (I'm kind of focusing on my actual project on the moment atm, so that binding generator has a lower priority for me).

**Comment by Pauan** [comment]
> 1. What are the components for the toolchain and wasm specification, necessary for such a project?

The current state-of-the-art is [stdweb](https://github.com/koute/stdweb), which dramatically simplifies compilation to webassembly, and also provides a fairly solid FFI to JS. It marshals Rust and JS data structures, so you can pass Rust stuff to JS and JS stuff to Rust.

> 2. How far along are they?

stdweb is still experimental and unstable (it *will* change), but it seems to work well so far. I've written a Chrome Extension (~4,000 lines of code) almost entirely in Rust (using stdweb).

> 3. What compromises/limitations would choosing this combination entail at which point in time?

Right now the biggest pain point is interop with JavaScript, which quite frankly sucks. You often need to use `Rc<RefCell<A>>` because JavaScript has a garbage collector and Rust doesn't. But it's doable, if you're willing to put up with a little bit of annoyance.

Also, the compiled webassembly is rather large (compared to equivalent JavaScript code), which is to be expected since Rust isn't optimized for code size.

**Comment by alexcrichton** [comment]
I think this issue is a bit dated at this point, so I'm going to close it.
